### ISSUE TITLE
Provide a better error message when there is no data in the star/end dates requested

### ISSUE THREAD

**Issue by torimcd** [podaac/hydrocron#127]
When you request a date range that contains no data you get a 404 page that looks like the API is down. We should make a more descriptive error message so people know to just choose different dates.

Found after updating to 2.0 data, the old URLs no longer work for dates in 2023:
https://soto.podaac.uat.earthdatacloud.nasa.gov/hydrocron/v1/timeseries?feature=Reach&feature_id=72390300011&start_time=2023-06-01T00:00:00Z&end_time=2023-10-30T00:00:00Z&output=geojson&fields=reach_id,time_str,wse,geometry

However dates in 2024 do work if they cover some period where there is data (for now that's between Jan 25 and Mar 27 2024):
https://soto.podaac.uat.earthdatacloud.nasa.gov/hydrocron/v1/timeseries?feature=Reach&feature_id=72390300011&start_time=2024-01-01T00:00:00Z&end_time=2024-10-30T00:00:00Z&output=geojson&fields=reach_id,time_str,wse,geometry

**Comment by nikki-t** [comment]
This is such odd behavior. I am not exactly sure what has been deployed to UAT but I wonder if the most recent error handling has been deployed? I don't think we have done a UAT release that includes those.

This SIT query returns a slightly better response: 
https://soto.podaac.sit.earthdatacloud.nasa.gov/hydrocron/v1/timeseries?feature=Reach&feature_id=73282400171&output=geojson&start_time=2022-07-28T00:00:00Z&end_time=2022-10-24T00:00:00Z&fields=reach_id,time_str,wse,slope 

Response:
```json
{
  "error" : "404: Results with the specified Feature ID 73282400171 were not found."
}
```

Maybe we can see what happens when we deploy to UAT and then modified as needed. Maybe there is a way to modify the API code to check the dates against the range for the current SWOT collection ingested into the Hydrocron database?

**Comment by nikki-t** [comment]
Okay I dug a little further and it looks like an error page is defined for the SOTO CloudFront Distribution in UAT but not in SIT. This error page points to a response page path of `/pages/404.html`.

I found this [documentation](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/GeneratingCustomErrorResponses.html#creating-custom-error-pages) on the error pages. It looks like the error page covers the entire distribution and is returned for all 404 errors. 

@frankinspace - Do you know who manages the CloudFront Distribution? And, I don't know much about CloudFront, maybe there is a way to customize the error pages based on origin?

**Comment by frankinspace** [comment]
Good catch; I hadn't considered the overlap in error codes. The 404 html error page is necessary for when a user inputs a path that doesn't exist (e.g. soto.podaac.earthdatacloud.nasa.gov/nothinghere) because the s3 default 404 page was flagged from NGAP's security scan.


@nikki-t the CloudFront Distribution is managed by the platform team. As far as I know the error page config is for the entire distro and can't be customized per-origin. I can think of 2 solutions:

1. Update hydrocron to return 400 Bad Request errors instead of 404 not found. This would bypass the cloudfront error mapping and simply return the content as provided directly from the API. I agree the 404 semantics are probably technically better for the "reach not found" use case but 400 seems like an ok choice too.
2. We could attempt to add some logic to do error handling; I think the appropriate place might be with lambda@edge function (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html#lambda-examples-update-error-status-examples) but last time I asked NGAP about that they said no one has tried using that feature before. 

Other thought; just browsing the documentation I don't see indicated anywhere that information about the original request being forwarded to the error page. I was wondering if maybe we could add some simple javascript logic to the 404.html page itself that might be able to render more details but from what I can tell, cloudfront just simply renders the 404 page directly without any additional context. Also, that would require the client actually execute javascript and with this being an API, most clients consuming the 404 page would likely not be running a javascript engine.


Sorry, bit of a brain dump there but long story short I think option 1 above would get us a quick win here.

**Comment by frankinspace** [comment]
Actually another option might be to remove the 404 mapping at cloudfront entirely and instead implement:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/CustomErrorDocSupport.html

Which _I think_ would result in a custom error page being returned from the s3 origin before reaching cloudfront; removing the need to have the 404 mapping in cloudfront. The only hiccup there is I don't think the s3 bucket origin is configured as a static website. It's unclear to me if this is a requirement of NGAP or another situation where no one has actually tried it yet and NGAP documentation is behind the curve.

**Comment by nikki-t** [comment]
@frankinspace - Thanks for all of the info! 

I had also looked at Lambda@Edge and saw that we could add logic to the error handling but it seems a little complicated for our use case. 

I am confused with how the CloudFront distribution is configured as it has an S3 bucket defined as an origin for error pages but I cannot locate an error page in that bucket. And I have no idea where the error page that is defined under the Error pages configuration is located. But, I understand what you are saying about the custom error page and the S3 origin.

I think either solution may be hard to test since it would require some iteration with NGAP on the CloudFront distribution.

For now, I will update the Hydrocron 404 error codes to 400 which I think is a good quick fix! Then I can move this ticket into the backlog and we can revisit when we have some time to work with NGAP on CloudFront. I am leaning towards testing the removal of the 404 mapping and using a S3 hosted custom error page.

**Comment by frankinspace** [comment]
> I am confused with how the CloudFront distribution is configured as it has an S3 bucket defined as an origin for error pages but I cannot locate an error page in that bucket. And I have no idea where the error page that is defined under the Error pages configuration is located. But, I understand what you are saying about the custom error page and the S3 origin.

The error pages s3 bucket origin on the distribution is an ngap-standard that they deploy with every CF distribution. The platform team offers a 'standard' 404 page as an option for tenants that can be served out of that origin. For SOTO we asked them to instead forward requests to the `/pages/404.html` path on the distribution instead, which ends up being resolved by the soto s3 bucket origin because of the default behavior of /* on the distro. So the source of `/pages/404.html` is actually https://github.com/podaac/worldview/blob/67039088b8d35d0c873af55780335ec0a0750b5d/web/pages/404.html. That page is built and included as part of the worldview app served from the soto s3 bucket.

Agree, discussion with NGAP about s3 error page would be required and not part of this issue. switch to 400 response code is 👍
