### ISSUE TITLE
Error message when incorrect time format entered suggests a time format that also fails

### ISSUE THREAD

**Issue by torimcd** [podaac/hydrocron#131]
Related to #129 , the error message when you enter the start or end date in the wrong format returns the following error message:
`"error" : "400: start_time and end_time parameters must conform to format: YYYY-MM-DDTHH:MM:SS+00:00"`

However, using the format `'YYYY-MM-DDTHH:MM:SS+00:00'` also fails. The only format that works as far as I know is `'YYYY-MM-DDTHH:MM:SSZ'`. We should update the error message to suggest using this format instead.

**Comment by nikki-t** [comment]
Makes sense and is an easy fix. One thing to think about is whether we want to require the `Z` at all?

The code uses the Python `strftime` and `strptime` format codes to check the dates:

```python
datetime.datetime.strptime(query_date, "%Y-%m-%dT%H:%M:%S%z")
```

where `%z` is the UTC offset which can be &pm;HH:MM or &pm;HHMM. And you can include `Z` to not include an offset. Do we think users will want to specify the offset?

If so, the `+` sign needs to be encoded (`%2b`) in order for it to be passed to the Lambda function in a valid form. So a valid query would be:

```bash
curl --location --request GET 'https://soto.podaac.sit.earthdatacloud.nasa.gov/hydrocron/v1/timeseries?feature=Reach&feature_id=63470800171&start_time=2024-02-01T00:00:00%2b00:00&end_time=2024-10-30T00:00:00%2b00:00&output=csv&fields=reach_id,time_str,wse'
```

Otherwise the dates are passed to the Lambda function with a space character replacing the `+` sign.

Maybe it makes sense to keep things as is and update the end user documentation and the error message to:

```bash
"error" : "400: start_time and end_time parameters must conform to format: 'YYYY-MM-DDTHH:MM:SSZ' or 'YYYY-MM-DDTHH:MM:SS%2b00:00'"
```
