### ISSUE TITLE
Remove obscure_data option from load data lambdas before OPS loading

### ISSUE THREAD

**Issue by torimcd** [podaac/hydrocron#161]
Some of the released data in uat has obscured values. It is a major issue to have bad data in what should be operational data. This can easily happen and is impossible to detect if at some point for even a single test the obscure_data input parameter on the loading lambdas is set to True. We should remove this input parameter prior to loading the ops database to ensure only good data is able to be loaded. If we keep the code in place that does the scrambling, but just remove the option to invoke it, we can easily put it back in for specific scenarios where we need to load simulated data in the future.

**Comment by nikki-t** [comment]
@torimcd - Did this happen because some tests were run in the UAT environment that loaded obscured data? How did it obscure the release data? Just wondering if we can isolate the cause and make sure it doesn't happen in the OPS environment.

Would it be more helpful to move the input parameter to an environment variable that gets set on the Lambda since that might be harder to modify? These can then be changed in the console or via the AWS CLI.

I think its fine to remove the input parameter option but it may be a little bit of a hassle if we wanted to load obscured data in UAT and need to deploy updated code to UAT to do so.

**Comment by torimcd** [comment]
@nikki-t yes, this is the only explanation I can think of that would have caused this. When the obscure_data parameter is True, all numerical measured fields get scaled by a random number between 2-9 when they're loaded into the database. It's a bit of a blunt tool in that it's not limited to what the bounds of the field are - it was only noticed because for some reaches, a quality flag field that only has values valid between 0-3 was reporting values between 4-16 for come reaches. Comparing to the source shapefile shows that all of the fields returned by hydrocron for a that timestep were off by the same factor. 

Moving to an environment variable instead of a lambda parameter makes sense to me, I'm fine with anything that makes it impossible to change accidentally in normal operations since there's no way to tell which data was affected.

We could also consider adding an _obscured_ field to the db records, and perhaps not expose it in the API response to avoid confusion and misinterpretation, but have it on-hand so we can quality check the data and find any records affected in the future?

**Comment by nikki-t** [comment]
@torimcd - Just to make sure I am understanding the `obscure_data` parameter (if set to `True`) will obscure all data in the database?

I think it makes sense to go with an `OBSCURE_DATA` environment variable that is set to `False` by default but we can then update via the console/CLI/SDK to `True` when we want to load benchmark testing data. So we can modify the code to test for the variable rather than for the `obscure_data` input parameter.

I also like the idea of having a database field that allows us to check if the data has been obscured so we can always trace the history of the various records.

**Comment by torimcd** [comment]
@nikki-t it won't affect existing data in the database, it will just obscure the specific granules that are being loaded in that invocation. So if it's set on the load_data lambda, any granule within the time range will be affected, and if it's on the load_granule lambda, just that single granule will be affected. 

Also this is totally separate from the benchmarking data, that is static data loaded from a dedicated CSV for a single reach that doesn't exist, so can't be discovered accidentally by users. It's possible that this happened during an attempt to load the benchmarking data if the wrong parameter was set to True.

**Comment by nikki-t** [comment]
Got it, thank you for clarifying! So when would we want to obscure the data?

**Comment by torimcd** [comment]
We used this to enable the first round of external beta testing before any of the SWOT data was released publicly. We opted to create our own 'simulated' data instead of using the pre-release simulated datasets since there were some anomalies in the formatting of some of the fields in the simulated data that were challenging to work around. This got us as close as possible to working with the real data, without exposing it publicly before it was released. Now that it's out, we don't ever want to use the obscured data in operations. But there could be a future scenario where we want to test with a new version, or a new product prior to release, which we might want to turn this back on for.

**Comment by nikki-t** [comment]
I see! I think the environment variable idea makes sense in the context of this. We would just have to remember to update the Lambda configuration to set the `OBSCURE_DATA` environment variable to `True`. Since we can define the environment variable in Terraform, if we ran Terraform (or complete a deployment) it would reset it back to `False` but I think since that is the norm it shouldn't present a problem. Totally open to other ideas too!
