### ISSUE TITLE
Add new option for the "feature" request parameter for prior lakes

### ISSUE THREAD

**Issue by frankinspace** [podaac/hydrocron#196]
- Update https://github.com/podaac/hydrocron/blob/develop/hydrocron/api/controllers/timeseries.py add new option called `PriorLake`
- Update documentation to describe new option
- Reuse `feature_id` request parameter to identify the lake being requested
- Update https://github.com/podaac/hydrocron/blob/develop/hydrocron/api/data_access/db.py to add new function which queries the new lake database table
- New/updated unit tests for `PriorLake` option

**Comment by nikki-t** [comment]
I am working on integrating lake queries into the API and ran into an issue with geometries. Did we settle on calculating the center points for each lake (#210)? If so that would be really useful to keep the API code clean and reduce complexity.

Right now, the geometries are returned as strings with a value of 'None' for lakes. If I don't include the geometry based on this then the JSON that is returned is not technically valid GeoJSON. However, if we calculate the center point and it gets stored as a Point type with corresponding coordinates then we can return valid GeoJSON assuming that is how we want to store the center point values.

I think it might make sense to implement the center point calculations first and then implement the API modifications. I can have everything defined and ready for the new lake data and will finalize the API implementation once the lake data center point operations are in place. 

@torimcd and @frankinspace - What do you think?

**Comment by torimcd** [comment]
@nikki-t yes we are going with center point calculations for #210, I'm working on that now. There is a weird issue where some of the reach_ids in the shapefiles don't have a geometry associated with them, that's why they are writing to the table as 'None'. Trying to figure out why those are in the **prior lake** files. I think there is one reach with a valid geometry loaded in SIT currently but you'll need to look at the table manually to find the id, that's the one to test with for now. 

Agree that we'll need to have #210 in place before finalizing the API modifications here, so maybe this gets paused for now until we're further along.

**Comment by nikki-t** [comment]
Thanks @torimcd - I tried to locate that prior lake with valid geometry but didn't see any lake data loaded in SIT (I may not be using DynamoDB correctly or misunderstood what data is loaded where). It sounds like there might be some overlap between the river table and the lake table? Either way, I am going to hold on this for now and wait until the centerpoints are in place.

**Comment by torimcd** [comment]
@nikki-t this is ready to continue with #210 resolved.
