### ISSUE TITLE
potentially missing dates in hydrocron for reach feature?

### ISSUE THREAD

**Issue by merrittharlan** [podaac/hydrocron#243]
https://soto.podaac.earthdatacloud.nasa.gov/hydrocron/v1/timeseries?feature=Reach&feature_id=81220100891&start_time=2023-07-01T00:00:00Z&end_time=2024-10-04T00:00:00Z&fields=reach_id,time_str,wse&output=csv 

I noticed that a reach in Alaska only has data through this June (and I expected a couple more months) -- do you all know why this might be the case? 

If you request data from a later start date, then it returns more values from June through September-- is there a date limit we should be aware of? https://soto.podaac.earthdatacloud.nasa.gov/hydrocron/v1/timeseries?feature=Reach&feature_id=81220100891&start_time=2024-01-01T00:00:00Z&end_time=2024-10-04T00:00:00Z&fields=reach_id,time_str,wse&output=csv

**Comment by nikki-t** [comment]
Thanks for bringing this to our attention @merrittharlan. After looking at the Hydrocron database I can see that the queries are not retrieving all of the records (which are essentially equal to time steps). I believe this has to do with how DynamoDB (the database back-end) [paginates table query results](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.Pagination.html).

The [API queries](https://github.com/podaac/hydrocron/blob/8aa3ec2840d4b7827c3c38e23c5bf7bfd96eb9dd/hydrocron/api/data_access/db.py#L22-L77) need to be modified to search for the `LastEvaluatedKey` in the database response and aggregate paginated results so that when a user queries Hydrocron all results are returned.

I will see if we can prioritize a fix for this.

**Comment by nikki-t** [comment]
@merrittharlan - We think we deployed a fix. Can you check to see on your end if this fixes the issue you were seeing?

Previously this query: https://soto.podaac.earthdatacloud.nasa.gov/hydrocron/v1/timeseries?feature=Reach&feature_id=81220100891&start_time=2023-07-01T00:00:00Z&end_time=2024-10-04T00:00:00Z&fields=reach_id,time_str,wse,granuleUR&output=geojson&compact=true 

was returning 84 records and now it is returning 112 which is what is present in the Hydrocron database.

**Comment by nikki-t** [comment]
Closing this as other folks have confirmed that they are pulling the full time series.

**Comment by merrittharlan** [comment]
Oops-- yes it has been working for me-- thanks for the quick fix!
