### ISSUE TITLE
Use a VPC endpoint and policies to access DynamoDB

### ISSUE THREAD

**Issue by frankinspace** [podaac/hydrocron#78]
Considered a security best practice:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/best-practices-security-preventative.html

Also theoretically would be performance improvement as connection would not traverse internet and stay within AWS network

**Comment by nikki-t** [comment]
It looks like VPC endpoints for DynamoDB have already been created in all three AWS accounts, so we do not need to create and manage our own endpoints. According to [this documentation]( https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/vpc-endpoints-dynamodb.html) we don't need to take any action for applications running on EC2 to use the endpoint.

I believe that our Lambda functions will need to be configured to use the VPC, so that Lambda traffic will traverse the DynamoDB endpoint. According to [this documentation]( https://docs.aws.amazon.com/lambda/latest/dg/configuration-vpc.html):

> By default, Lambda runs your functions in a secure VPC with access to AWS services and the internet. Lambda owns this VPC, which isn't connected to your account's default VPC.

Is there a benefit to configuring our Lambda functions to connect to private subnets in the VPC so that they use the DynamoDB endpoint? 

It seems that traffic is secure out of the box and is configured in a similar way to how we would configure it using a VPC as EC2 traffic will use the endpoint and we would still allow outbound Internet traffic. I am also not sure if there is a cost benefit to this.

That being said maybe there is some benefit to isolating all of our DynamoDB traffic to a single VPC. 

@frankinspace and @torimcd - Do you have any thoughts on configuring the Lambda to use the VPC?

**Comment by frankinspace** [comment]
I think we would still benefit from defining the VPC endpoint. Although the VPC is secured, as far as I can tell requests will still traverse the internet to make it to dynamodb without the VPC endpoint. With the VPC endpoint defined and the lambda deployed to our VPC, requests from lambda -> dynamo should stay entirely within our VPC and theoretically have improved request latency.

Still worth a shot I think to see if we can get the VPC endpoint to work.

**Comment by nikki-t** [comment]
It looks like NGAP already defines DynamoDB VPC Endpoints in all three AWS environment. I don't think we can define and use our own endpoint within the NGAP VPC because all of the routing is already set up. So, I will plan to configure the three Lambda functions (timeseries, load_data, and load_data - granule) to connect to the NGAP VPC which should force the Lambda traffic to use the DynamoDB endpoint and remain within the same VPC.
